name = "Blaze"
uuid = "d9380286-669a-4c80-beba-0bb7d51c4fc0"
authors = ["jason89757"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
